# Generated by Django 5.0.6 on 2024-05-25 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.IntegerField(blank=True, choices=[(60, '60ml'), (100, '100ml'), (120, '120ml')], null=True),
        ),
    ]
